language: node_js
node_js:
  - "7.6"
  - "8.9"
services:
  - mongodb
cache:
  directories:
    - node_modules
git:
  depth: 3
script:
  - yarn cover:check
after_script:
  - yarn report
# after_success:
#   - yarn build
